import classNames from "classnames";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito-sans",
});

export const metadata: Metadata = {
  title: "BookWise",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt-BR">
      <body
        className={classNames(
          "text-app-gray-100 bg-app-gray-800 p-5 font-sans",
          nunitoSans.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
